services:
  my-jenkins:
    image: my-jenkins
    container_name: my-jenkins
    restart: on-failure
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Do not include DOCKER_TLS_VERIFY or DOCKER_CERT_PATH here if you're not using TLS
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
