version: "3.7"

services:
  my-jenkins:
    image: my-jenkins
    container_name: my-jenkins
    restart: on-failure
    environment:
      # Update the DOCKER_HOST to point to the Unix socket on the host.
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins-data:/var/jenkins_home
      # Mount the host's Docker socket so that docker commands run inside the container affect the host daemon.
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
